# app/models/symbols.py
from pydantic import BaseModel

class SymbolInfo(BaseModel):
    name: str
    path: str
    description: str
    currency_base: str
    currency_profit: str
    currency_margin: str
    digits: int
    spread: int
    spread_float: float
    ticks_bookdepth: int
    trade_calc_mode: int
    trade_mode: int
    start_time: int
    expiration_time: int
    trade_start: int
    trade_end: int
    min_lot: float
    max_lot: float
    lot_step: float
    volume_min: float
    volume_max: float
    volume_step: float
    volume_limit: float
    swap_long: float
    swap_short: float
    swap_rollover3days: int
    margin_initial: float
    margin_maintenance: float
    margin_hedged: float
    margin_long: float
    margin_short: float
    margin_limit: float
    margin_stopout_initial: float
    margin_stopout_maintenance: float
    margin_stopout_hedged: float
    session_hedged_margin: float
    price_limit_kind: int
    price_limit_offset: float
    price_freeze_level: int
    trade_contract_size: float
    trade_accrued_interest: float
    trade_face_value: float
    trade_liquidity_rate: float
    trade_basis: float
    trade_rebate: float
    trade_commission_base: float
    trade_commission_leg: float
    trade_commission_point: float
    trade_commission_mode: int
    trade_options: int
    trade_exec_mode: int
    swap_mode: int
    swap_rollover3days_mode: int
    margin_flags: int
    hedge_flags: int
    trade_flags: int
    flags: int
    trade_mode3: int
    filling_mode: int
    order_mode: int
    expiration_mode: int
    swap_rollover_mode: int
    swap_rollover_days: list[int]
    margin_currency: str
    margin_mode: int
    margin_option: int
    background_color: int
    chart_mode: int
    chart_mode_bars: int
    chart_color_bg: int
    chart_color_bg2: int
    chart_color_bg3: int
    chart_color_grid: int
    chart_color_cross: int
    chart_color_text: int
    chart_color_candle_bull: int
    chart_color_candle_bear: int
    chart_color_candle_stable: int
    chart_color_wick_stable: int
    chart_scale_font: int
    chart_scale_filter: int
    chart_fixed_max: float
    chart_fixed_min: float
    chart_auto_scale: int
    chart_price_max: float
    chart_price_min: float
    chart_price_fixed_max: float
    chart_price_fixed_min: float
    chart_price_min_deviation: float
    chart_price_max_deviation: float
    chart_fixed_max_deviation: float
    chart_fixed_min_deviation: float
    chart_auto_scale_deviation: int
    chart_price_deviation: float
    chart_price_deviation_in_pips: int
    chart_price_deviation_in_percent: float
    chart_price_deviation_in_points: float
    chart_price_deviation_in_bars: int
    chart_price_deviation_in_seconds: int
    chart_price_deviation_in_minutes: int
    chart_price_deviation_in_hours: int
    chart_price_deviation_in_days: int
    chart_price_deviation_in_weeks: int
    chart_price_deviation_in_months: int
    chart_price_deviation_in_years: int
    chart_price_deviation_in_ticks: int
    chart_price_deviation_in_volumes: int
    chart_price_deviation_in_spreads: int
    chart_price_deviation_in_averages: int
    chart_price_deviation_in_ranges: int
    chart_price_deviation_in_levels: int
    chart_price_deviation_in_patterns: int
    chart_price_deviation_in_indicators: int
    chart_price_deviation_in_scripts: int
    chart_price_deviation_in_functions: int
    chart_price_deviation_in_events: int
    chart_price_deviation_in_news: int
    chart_price_deviation_in_alerts: int
    chart_price_deviation_in_reports: int
    chart_price_deviation_in_experts: int
    chart_price_deviation_in_signals: int
    chart_price_deviation_in_optimization: int
    chart_price_deviation_in_backtesting: int
    chart_price_deviation_in_strategy_testing: int
    chart_price_deviation_in_visualization: int
    chart_price_deviation_in_reporting: int
    chart_price_deviation_in_analysis: int
    chart_price_deviation_in_research: int
    chart_price_deviation_in_development: int
    chart_price_deviation_in_training: int
    chart_price_deviation_in_simulation: int
    chart_price_deviation_in_simulation_mode: int
    chart_price_deviation_in_simulation_period: int
    chart_price_deviation_in_simulation_data: int
    chart_price_deviation_in_simulation_results: int
    chart_price_deviation_in_simulation_statistics: int
    chart_price_deviation_in_simulation_visualization: int
    chart_price_deviation_in_simulation_reporting: int
    chart_price_deviation_in_simulation_analysis: int
    chart_price_deviation_in_simulation_research: int
    chart_price_deviation_in_simulation_development: int
    chart_price_deviation_in_simulation_training: int
    chart_price_deviation_in_simulation_simulation: int
    chart_price_deviation_in_simulation_simulation_mode: int
    chart_price_deviation_in_simulation_simulation_period: int
    chart_price_deviation_in_simulation_simulation_data: int
    chart_price_deviation_in_simulation_simulation_results: int
    chart_price_deviation_in_simulation_simulation_statistics: int
    chart_price_deviation_in_simulation_simulation_visualization: int
    chart_price_deviation_in_simulation_simulation_reporting: int
    chart_price_deviation_in_simulation_simulation_analysis: int
    chart_price_deviation_in_simulation_simulation_research: int
    chart_price_deviation_in_simulation_simulation_development: int
    chart_price_deviation_in_simulation_simulation_training: int
    chart_price_deviation_in_simulation_simulation_simulation: int

class TickInfo(BaseModel):
    time: int
    bid: float
    ask: float
    last: float
    volume: int
    time_msc: int
    flags: int
    volume_real: float